### PR TITLE
Properly handle queries without `_time`

### LINKED ISSUE #1758: Fix dygraphs parsing of Flux responses without a `_time` column
Some Flux queries return `_start` and `_stop` columns, but no `_time` column. For example:

```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "mem")
  |> filter(fn: (r) => r._field == "active")
  |> mean()
```

The Data Explorer currently crashes when attempting to view such a query. The error message is:
```
Could not find time index in FluxTable
```

### PR DESCRIPTION
**Pull request by bthesorceror**
Closes #1758 

  - [x] Rebased/mergeable
  - [x] Tests pass
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: ui/src/shared/parsing/flux/dygraph.ts [hunk 1]
```diff
@@ -59,7 +79,7 @@ export const fluxTablesToDygraph = (
       allColumnNames.push(uniqueColumnName)
     }
 
-    const timeIndex = header.indexOf('_time')
+    const timeIndex = getTimeIndex(header)
```
Comment (OfTheDelmer) [inline ui/src/shared/parsing/flux/dygraph.ts]: @bthesorceror Note one query I often write still doesn't work with these fixes

```
from(bucket: "telegraf/autogen")
	|> filter(fn: (r) => r._measurement == "syslog")
    |> range(start: -1m)
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> group()
    |> map(fn: (r) => {message: r.message})
```

Returns

```
#datatype,string,long,string
#group,false,false,false
#default,_result,,
,result,table,message
,,0,"﻿Try to compress the AI transmitter, maybe..."
```

Comment (OfTheDelmer) [reply ui/src/shared/parsing/flux/dygraph.ts]: Note assuming `fromRows` works this could just be

```
fromRows(bucket: "telegraf/autogen")
    |> filter(fn: (r) => r._measurement == "syslog")
    |> range(start: -1m)
    |> group() 
    |> map(fn: (r) => {message: r.message})
```
