### PR TITLE
fix(http): links updated to match swagger doc

### LINKED ISSUE #939: Update /healthz endpoint in code to match /health as per swagger
The swagger docs mention a `/health` endpoint, but in the code it's currently `/healthz`. Personally I think `/health` is nicer, though I understand there's historical context for `/healthz`.

### LINKED ISSUE #956: Add views to link to /api/v2
Log viewer stores its log viewer properties as a view using `/api/v2/views`. However, the response from `/api/v2` does not include a `views` link that can be provided to the log viewer.

### PR DESCRIPTION
**Pull request by goller**
Closes #956
Closes #939 

_Briefly describe your proposed changes:_
The go code for some routes and some links were out of date as compared to the swagger.

_What was the problem?_
View and macros were not in the links and healthz should have been health.

_What was the solution?_
Flux links are now scoped under query:

```
/api/v2/query/ast
/api/v2/query/suggests
/api/v2/query/spec
```

View link is now available:

```
/api/v2/views
```

Macros link is:

```
/api/v2/macros
```

Health link is now

```
/api/v2/health
```

  - [ ] CHANGELOG.md updated with a link to the PR (not the Issue)
  - [x] Rebased/mergeable
  - [ ] Tests pass
  - [x] swagger.json updated (if modified Go structs or API)
  - [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: chronograf/ui/src/types/v2/links.ts [hunk 1]
```diff
@@ -1,22 +1,28 @@
...
 export interface Links {
   auths: string
   buckets: string
   dashboards: string
   external: {
     statusFeed: string
   }
-  flux: {
-    ast: string
+  query: {
```
Comment (OfTheDelmer) [inline chronograf/ui/src/types/v2/links.ts]: Nice
