### PR TITLE
fix(http): pass user service to handler New function

### LINKED ISSUE #1987: owner/member endpoints are timing out
Introduced by https://github.com/influxdata/platform/pull/1486:

`UserService` is being used in the `NewTaskHandler` method for `BucketService`, `DashboardService`, `OrganizationService` and `TaskService` before it's been assigned.

### PR DESCRIPTION
**Pull request by zhulongcheng**
Closes #1987

### CODE REVIEW

**Comment by zhulongcheng** [comment]
Hi @jademcgough , Do you mind giving a review?

File: http/api_handler.go [hunk 1]
```diff
@@ -72,30 +72,26 @@ func NewAPIHandler(b *APIBackend) *APIHandler {
 	h.SessionHandler.SessionService = b.SessionService
 	h.SessionHandler.Logger = b.Logger.With(zap.String("handler", "basicAuth"))
 
-	h.BucketHandler = NewBucketHandler(b.UserResourceMappingService, b.LabelService)
+	h.BucketHandler = NewBucketHandler(b.UserResourceMappingService, b.LabelService, b.UserService)
```
Comment (desa) [inline http/api_handler.go]: What do you think about having a config struct for each of these handlers? So that when we want to add more services to a new handler we don't have to modify the function signature?

Comment (zhulongcheng) [reply http/api_handler.go]: Great idea!  💯

Comment (zhulongcheng) [reply http/api_handler.go]: Can I  finish those changes in a new PR?  A config for each handler.

Comment (desa) [reply http/api_handler.go]: That works for me 👍
