### PR TITLE
Fix issue#1467

### LINKED ISSUE #1467: Can't POST to /api/v2/query with a session cookie
I have a valid session, and I'm attempting to run a query via:

```
curl -v -X POST 'http://localhost:9999/api/v2/query' \
  -H "Cookie: session=$INFLUX_SESSION" \
  -d '{"query":"from(bucket: \"telegraf\")\n  |> range(start: -1m)"}'
```
I receive the error
```
X-Influx-Error: authorization not found
```

If I use an invalid session, I receive a different error:
```
X-Influx-Error: unauthorized
```

However, using a `Authorization` header works fine:
```
curl -v -X POST 'http://localhost:9999/api/v2/query' \
  -H "Authorization: Token $INFLUX_TOKEN" \
  -d '{"query":"from(bucket: \"telegraf\")\n  |> range(start: -1m)"}'
```

I can also query other endpoints just fine using a session (e.g. `/api/v2/orgs`).

### PR DESCRIPTION
**Pull request by desa**
Closes #1467 

_Briefly describe your proposed changes:_
This PR introduces a mechanism for turning a user resource mapping into a set of permissions that can be used to authorize requests. Additionally, it removes the write endpoints dependence on the authorization service and uses the authorizer middleware instead.

  - [x] Rebased/mergeable
  - [x] Tests pass

### CODE REVIEW

File: user_resource_mapping.go [hunk 1]
```diff
@@ -66,3 +67,33 @@ type UserResourceMappingFilter struct {
 	UserID       ID
 	UserType     UserType
 }
+
+var ownerActions = []action{WriteAction, CreateAction, DeleteAction}
+var memberActions = []action{ReadAction}
+
+// ToPermission converts a user resource mapping into a set of permissions.
+func (m *UserResourceMapping) ToPermissions() []Permission {
```
Comment (kelwang) [inline user_resource_mapping.go]: maybe use a map [resource]permission, so it's o(1) for search
