### PR TITLE
Fix/org view

### LINKED ISSUE #2182: Use dashboard modified date in the UI
as a platform user
with viewer permissions or higher
when i view the list of dashboards 
then i would like to see the last time they were updated

### PR DESCRIPTION
**Pull request by 121watts**
Closes #2182

### CODE REVIEW

File: ui/src/dashboards/components/dashboard_index/Table.tsx [hunk 1]
```diff
@@ -133,6 +128,13 @@ class DashboardsTable extends PureComponent<Props & WithRouterProps, State> {
     return null
   }
 
+  private get datedDashboards(): DatedDashboard[] {
+    return this.props.dashboards.map(d => ({
+      ...d,
+      modified: new Date(d.meta.updatedAt),
```
Comment (ebb-tide) [inline ui/src/dashboards/components/dashboard_index/Table.tsx]: is this not meant to be time since update? which is silly but.
