### PR TITLE
fix(storage): avoid data race on table Done channel

### LINKED ISSUE #1021: Data race in storage when querying
Got this when executing a simple query: `from(bucket:"demo-bucket-in-1") |> range(start:-5s)`

```
==================
WARNING: DATA RACE
Write at 0x00c0004d7418 by goroutine 31:
  github.com/influxdata/platform/storage/reads.(*floatTable).Close()
      /Users/mr/gomod/platform/storage/reads/table.gen.go:52 +0xb8
  github.com/influxdata/platform/storage/reads.(*floatTable).Do()
      /Users/mr/gomod/platform/storage/reads/table.gen.go:70 +0x138
  github.com/influxdata/flux/csv.(*ResultEncoder).Encode.func1()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/csv/result.go:790 +0x97e
  github.com/influxdata/flux/execute.(*result).Do()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/execute/result.go:71 +0x1cd
  github.com/influxdata/flux/csv.(*ResultEncoder).Encode()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/csv/result.go:748 +0x676
  github.com/influxdata/flux.(*DelimitedMultiResultEncoder).Encode()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/result.go:183 +0x1a6
  github.com/influxdata/platform/query.ProxyQueryServiceBridge.Query()
      /Users/mr/gomod/platform/query/bridges.go:36 +0x138
  github.com/influxdata/platform/query.(*ProxyQueryServiceBridge).Query()
      <autogenerated>:1 +0xb5
  github.com/influxdata/platform/http.(*FluxHandler).handlePostQuery()
      /Users/mr/gomod/platform/http/query_handler.go:91 +0x360
  github.com/influxdata/platform/http.(*FluxHandler).handlePostQuery-fm()
      /Users/mr/gomod/platform/http/query_handler.go:51 +0x5f
  net/http.HandlerFunc.ServeHTTP()
      /Users/mr/gotip/src/github.com/golang/go/src/net/http/server.go:1986 +0x4c
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /Users/mr/go/pkg/mod/github.com/julienschmidt/httprouter@v0.0.0-20180222160526-d18983907793/router.go:334 +0xe56
  github.com/influxdata/platform/http.(*APIHandler).ServeHTTP()
      /Users/mr/gomod/platform/http/api_handler.go:189 +0xeb0
  github.com/influxdata/platform/http.(*AuthenticationHandler).ServeHTTP()
      /Users/mr/gomod/platform/http/authentication_middleware.go:85 +0x739
  github.com/influxdata/platform/http.(*PlatformHandler).ServeHTTP()
      /Users/mr/gomod/platform/http/platform_handler.go:59 +0x120
  github.com/influxdata/platform/http.(*Handler).ServeHTTP()
      /Users/mr/gomod/platform/http/handler.go:159 +0x41c
  net/http.serverHandler.ServeHTTP()
      /Users/mr/gotip/src/github.com/golang/go/src/net/http/server.go:2763 +0xc4
  net/http.(*conn).serve()
      /Users/mr/gotip/src/github.com/golang/go/src/net/http/server.go:1869 +0x804

Previous read at 0x00c0004d7418 by goroutine 148:
  github.com/influxdata/platform/storage/reads.(*table).Done()
      /Users/mr/gomod/platform/storage/reads/table.go:56 +0x3e
  github.com/influxdata/platform/storage/reads.(*floatTable).Done()
      <autogenerated>:1 +0x43
  github.com/influxdata/platform/storage/reads.(*tableIterator).handleRead()
      /Users/mr/gomod/platform/storage/reads/reader.go:174 +0x487
  github.com/influxdata/platform/storage/reads.(*tableIterator).Do()
      /Users/mr/gomod/platform/storage/reads/reader.go:124 +0xa15
  github.com/influxdata/flux/functions/inputs/storage.(*source).run()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/functions/inputs/storage/storage.go:105 +0x15b
  github.com/influxdata/flux/functions/inputs/storage.(*source).Run()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/functions/inputs/storage/storage.go:96 +0x59
  github.com/influxdata/flux/execute.(*executionState).do.func1()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/execute/executor.go:221 +0x7c

Goroutine 31 (running) created at:
  net/http.(*Server).Serve()
      /Users/mr/gotip/src/github.com/golang/go/src/net/http/server.go:2873 +0x4c2
  net/http.(*Server).ListenAndServe()
      /Users/mr/gotip/src/github.com/golang/go/src/net/http/server.go:2786 +0xe5
  main.platformF.func2()
      /Users/mr/gomod/platform/cmd/influxd/main.go:353 +0x3d5

Goroutine 148 (finished) created at:
  github.com/influxdata/flux/execute.(*executionState).do()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/execute/executor.go:202 +0xce
  github.com/influxdata/flux/execute.(*executor).Execute()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/execute/executor.go:74 +0x10b
  github.com/influxdata/flux/control.(*Controller).processQuery()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/control/controller.go:321 +0x357
  github.com/influxdata/flux/control.(*Controller).run()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.0.0-20181004191346-fe166147b764/control/controller.go:253 +0x375
==================
```

The data race seems to be reliably reproducible.

Setup: using https://github.com/mark-rushakoff/taskdemo at commit `bc5c886bbb8b295b331981afd899621e4f0d9dd4`, run `go run ./main.go 1 write` in one terminal, and while it's still writing, run `go run ./main.go 1 read-in` in another terminal.

### PR DESCRIPTION
**Pull request by mark-rushakoff**
Fixes #1021.

### CODE REVIEW

File: storage/reads/reader.go [hunk 1]
```diff
@@ -166,12 +166,16 @@ READ:
 			continue
 		}
 
+		// Evaluate table.Done early to avoid a data race if table.Close() is run on another goroutine
```
Comment (e-dard) [inline storage/reads/reader.go]: I don't have the entire context on this but can't the `table.Close` on line 165 also cause this problem if `handleRead` is called in another goroutine? I don't understand why the `table.Close()` on 174 is problematic but the one on 165 isn't

Comment (mark-rushakoff) [reply storage/reads/reader.go]: It very well could be a data race, but I haven't been able to trigger that one. I somewhat suspect a better long-term solution would be to not reassign `table.done` in close, maybe using a sync.Once instead. But I'm not familiar enough with this area of the code - I just did the bare minimum to eliminate a data race that I was able to reliably reproduce through a very basic use case.
